name = "YOUR_PAGES_PROJECT_NAME"
compatibility_date = "2026-02-03"

# You might have other config above here
# Do NOT have any placeholder in database_id

[[d1_databases]]
binding = "DB"
database_name = "xoo-db"
database_id = "d820877d-f533-4a23-a406-8d6a07367e4b"
